package:
  name: pynio
  version: "1.5.0beta"

source:
  path: ../src/pynio-1.5.0-beta

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libpng 
    - jasper
    - jpeg
    - zlib
    - hdf4
    - hdf5
    - numpy
    - gcc
    - python
    - libnetcdf
    - proj4
    - hdfeos2
    - g2clib
    - gdal
    - libiconv
    - hdfeos5 
    - libpng
    - curl

  run:
    - libgcc
    - libpng
    - jasper
    - jpeg
    - zlib
    - numpy
    - python
    - libnetcdf
    - hdf5
    - hdf4
    - proj4
    - hdfeos2
    - g2clib
    - gdal
    - libiconv
    - hdfeos5
    - libpng
    - curl

test:
  requires:
    - nose
  imports:
    - Nio
  commands:
    - cd $SRC_DIR/test && nosetests -s

